In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'E:\DEPI\Competion $$$\archive\usa_county_wise.csv')

In [4]:
df.shape

(627920, 14)

In [5]:
df.head()

,UID,iso2,iso3,code3,FIPS,Admin2,Province_State,Country_Region,Lat,Long_,Combined_Key,Date,Confirmed,Deaths
0,16,AS,ASM,16,60.0,NaN,American Samoa,US,-14.271000,-170.132000,"American Samoa, US",1/22/20,0,0
1,316,GU,GUM,316,66.0,NaN,Guam,US,13.444300,144.793700,"Guam, US",1/22/20,0,0
2,580,MP,MNP,580,69.0,NaN,Northern Mariana Islands,US,15.097900,145.673900,"Northern Mariana Islands, US",1/22/20,0,0
3,63072001,PR,PRI,630,72001.0,Adjuntas,Puerto Rico,US,18.180117,-66.754367,"Adjuntas, Puerto Rico, US",1/22/20,0,0
4,63072003,PR,PRI,630,72003.0,Aguada,Puerto Rico,US,18.360255,-67.175131,"Aguada, Puerto Rico, US",1/22/20,0,0

In [6]:
df.columns

Index(['UID', 'iso2', 'iso3', 'code3', 'FIPS', 'Admin2', 'Province_State',
       'Country_Region', 'Lat', 'Long_', 'Combined_Key', 'Date', 'Confirmed',
       'Deaths'],
      dtype='object')

In [7]:
df = df[['Province_State',
       'Lat', 'Long_', 'Combined_Key', 'Date', 'Confirmed',
       'Deaths']]

In [8]:
df.head()

,Province_State,Lat,Long_,Combined_Key,Date,Confirmed,Deaths
0,American Samoa,-14.271000,-170.132000,"American Samoa, US",1/22/20,0,0
1,Guam,13.444300,144.793700,"Guam, US",1/22/20,0,0
2,Northern Mariana Islands,15.097900,145.673900,"Northern Mariana Islands, US",1/22/20,0,0
3,Puerto Rico,18.180117,-66.754367,"Adjuntas, Puerto Rico, US",1/22/20,0,0
4,Puerto Rico,18.360255,-67.175131,"Aguada, Puerto Rico, US",1/22/20,0,0

In [9]:
df['City'] = df['Combined_Key'].str.split(',').str[0]
df['City']

0                   American Samoa
1                             Guam
2         Northern Mariana Islands
3                         Adjuntas
4                           Aguada
                    ...
627915                Central Utah
627916              Southeast Utah
627917              Southwest Utah
627918                   TriCounty
627919                Weber-Morgan
Name: City, Length: 627920, dtype: object

In [10]:
df.head()

,Province_State,Lat,Long_,Combined_Key,Date,Confirmed,Deaths,City
0,American Samoa,-14.271000,-170.132000,"American Samoa, US",1/22/20,0,0,American Samoa
1,Guam,13.444300,144.793700,"Guam, US",1/22/20,0,0,Guam
2,Northern Mariana Islands,15.097900,145.673900,"Northern Mariana Islands, US",1/22/20,0,0,Northern Mariana Islands
3,Puerto Rico,18.180117,-66.754367,"Adjuntas, Puerto Rico, US",1/22/20,0,0,Adjuntas
4,Puerto Rico,18.360255,-67.175131,"Aguada, Puerto Rico, US",1/22/20,0,0,Aguada

In [11]:
df = df[(df['Confirmed'] >= 1) & (df['Deaths'] >= 1)]

In [12]:
df.head()

,Province_State,Lat,Long_,Combined_Key,Date,Confirmed,Deaths,City
129971,Washington,47.491379,-121.834613,"King, Washington, US",2/29/20,6,1,King
133311,Washington,47.491379,-121.834613,"King, Washington, US",3/1/20,9,1,King
136651,Washington,47.491379,-121.834613,"King, Washington, US",3/2/20,14,5,King
136665,Washington,48.046160,-121.717070,"Snohomish, Washington, US",3/2/20,4,1,Snohomish
139991,Washington,47.491379,-121.834613,"King, Washington, US",3/3/20,21,6,King

In [14]:
df.columns

Index(['Province_State', 'Lat', 'Long_', 'Combined_Key', 'Date', 'Confirmed',
       'Deaths', 'City'],
      dtype='object')

In [15]:
df = df[['Province_State', 'Lat', 'Long_', 'Date', 'Confirmed',
       'Deaths', 'City']]

In [16]:
df.head()

,Province_State,Lat,Long_,Date,Confirmed,Deaths,City
129971,Washington,47.491379,-121.834613,2/29/20,6,1,King
133311,Washington,47.491379,-121.834613,3/1/20,9,1,King
136651,Washington,47.491379,-121.834613,3/2/20,14,5,King
136665,Washington,48.046160,-121.717070,3/2/20,4,1,Snohomish
139991,Washington,47.491379,-121.834613,3/3/20,21,6,King

In [13]:
#df.to_csv('USA_Covid19.csv', index=False)